# CDR-001: Coder Enterprise license key
# Pulls coder4gov/coder-license from AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-license
  namespace: coder
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: coder-license
    creationPolicy: Owner
  data:
    - secretKey: license
      remoteRef:
        key: coder4gov/coder-license
